### ISSUE TITLE
Arbitrary clip shapes

### ISSUE THREAD

**Issue by Kethku** [neovide/vide#6]
Layers can only be clipped by axis aligned rectangles currently. For usecases like rendering characters within cursor paths in neovide, we need to be able to clip to an arbitrary shape.

It is unclear whether this should be done via a clipping mask, rendering to an offscreen texture that is then rendered to triangles computed by lyon or some other approach

**Comment by fredizzimo** [comment]
I think we also need to support different clipping regions within the same layer. Consider the drawing of floating windows with borders. we first draw the borders, then the inner region with a clipping rectangle. 

It seems a bit wasteful to create a new layer for this, but maybe that's not a problem depending on the implementation.

**Comment by Kethku** [comment]
I've been thinking about this and I think if we can do it performance wise limiting cliping to layers would make the model overall simple. So I'd personally like to try getting arbitrary clipping working with just that, but I'm not super attached to the idea

**Comment by Kethku** [comment]
Complete
